char = "#"

print(f" {char*5}")
print(f"{char} ")
print(f"{char} ")
print(f"{char} ")
print(f" {char*5}")
print(" ")
print(f" {char*4}")
print(f"{char}    {char}")
print(f"{char}    {char}")
print(f"{char}    {char}")
print(f" {char*4}")
print(" ")
print(f"{char*4}")
print(f"{char}   {char}")
print(f"{char}    {char}")
print(f"{char}   {char}")
print(f"{char*4}")
print(" ")
print(f"{char*5}")
print(f"{char}")
print(f" {char*4}")
print(f"{char}")
print(f"{char*5}")
